"""Ajout de descriptions aux board

Revision ID: 3417cd21d875
Revises: 
Create Date: 2025-04-02 08:09:15.654876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3417cd21d875'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Board_id', table_name='Board')
    op.drop_index('ix_Board_owner_id', table_name='Board')
    op.drop_table('Board')
    op.drop_index('ix_User_email', table_name='User')
    op.drop_index('ix_User_id', table_name='User')
    op.drop_table('User')
    op.drop_index('ix_TaskList_board_id', table_name='TaskList')
    op.drop_index('ix_TaskList_id', table_name='TaskList')
    op.drop_table('TaskList')
    op.drop_index('ix_Task_id', table_name='Task')
    op.drop_index('ix_Task_list_id', table_name='Task')
    op.drop_table('Task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Task',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('list_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Task_list_id', 'Task', ['list_id'], unique=False)
    op.create_index('ix_Task_id', 'Task', ['id'], unique=False)
    op.create_table('TaskList',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('board_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_TaskList_id', 'TaskList', ['id'], unique=False)
    op.create_index('ix_TaskList_board_id', 'TaskList', ['board_id'], unique=False)
    op.create_table('User',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('firstname', sa.VARCHAR(), nullable=True),
    sa.Column('lastname', sa.VARCHAR(), nullable=True),
    sa.Column('password', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_User_id', 'User', ['id'], unique=False)
    op.create_index('ix_User_email', 'User', ['email'], unique=1)
    op.create_table('Board',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('positionX', sa.INTEGER(), nullable=True),
    sa.Column('positionY', sa.INTEGER(), nullable=True),
    sa.Column('sizeX', sa.INTEGER(), nullable=True),
    sa.Column('sizeY', sa.INTEGER(), nullable=True),
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_Board_owner_id', 'Board', ['owner_id'], unique=False)
    op.create_index('ix_Board_id', 'Board', ['id'], unique=False)
    # ### end Alembic commands ###
